
package com.unsada.pbo;

import com.unsada.pbo.database.InitialData;
import com.unsada.pbo.masterData.Kasir;
import com.unsada.pbo.masterData.Minimarket;
import com.unsada.pbo.masterData.Produk;
import com.unsada.pbo.util.Penjualan;
import com.unsada.pbo.util.Transaksi;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {
    private Minimarket minimarket;
    private Kasir chasier;
    private Transaksi transaksi;
    private Produk[] listProduk;
    
    private CardLayout cardLayout;
    private CardLayout mainMenuCardLayout;
    private CardLayout belanjaCardLayout;
    private JFrame msgbox;
    /**
     * Creates new form GUI
     */
    public Main() {
        
        initComponents();
        setTitle("Easy SHopping in Minimarket");
        minimarket = new Minimarket(InitialData.getInitialCashiers(),
    			InitialData.getInitialProducts(), new ArrayList<>());
        cardLayout = (CardLayout) (mainContainer.getLayout());
        mainMenuCardLayout = (CardLayout) (mainMenuCardContainer.getLayout());
        belanjaCardLayout = (CardLayout) (belanjaCardContainer.getLayout());
//        this.keranjangTextArea.setEditable(false);
//        a.toArray(new TypeA[a.size()]);
        this.listProduk = minimarket.getProducts().toArray(new Produk[this.minimarket.getProducts().size()]);
//        minimarket.getProducts().toArray(this.listProduk);
        
        produkComboBox.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if(value instanceof Produk ){
                    Produk produk = Produk.class.cast(value);
                    setText(produk.getNamaProduk()+ " (Rp."+produk.getHargaProduk()+") | Sisa stok : "+produk.getStokProduk());
                }
                return this;
            }
        } );
        returComboBox.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if(value instanceof Produk){
                     Produk produk = Produk.class.cast(value);
                    setText(produk.getNamaProduk());
                }
                return this;
            }
        });
        restockComboBox.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if(value instanceof Produk ){
                     Produk produk = Produk.class.cast(value);
                    setText(produk.getNamaProduk());
                }
                return this;
            }
        } );
        hapusProdukComboBox.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if(value instanceof Produk ){
                     Produk produk = Produk.class.cast(value);
                    setText(produk.getNamaProduk());
                }
                return this;
            }
        } );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        unameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        unameTextField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        unameStatus = new javax.swing.JLabel();
        passStatus = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        mainMenuPanel = new javax.swing.JPanel();
        mainMenuLabel = new javax.swing.JLabel();
        belanjaButton = new javax.swing.JButton();
        showTransactionsButton = new javax.swing.JButton();
        restockButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        hapusProdukButton = new javax.swing.JButton();
        tambahProdukBaruButton = new javax.swing.JButton();
        mainMenuCardContainer = new javax.swing.JPanel();
        firstPanelMainMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        transaksiPanel = new javax.swing.JPanel();
        daftarTransaskiLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaksiTextArea = new javax.swing.JTextArea();
        restockPanel = new javax.swing.JPanel();
        restockProdukLabel = new javax.swing.JLabel();
        produkRestockLabel = new javax.swing.JLabel();
        restockComboBox = new javax.swing.JComboBox<>();
        jumlahRestockLabel = new javax.swing.JLabel();
        stokRestockLabel = new javax.swing.JLabel();
        restockJumlahTextField = new javax.swing.JTextField();
        restockProductButton = new javax.swing.JButton();
        restockJumlahLabel = new javax.swing.JLabel();
        tambahProdukBaruPanel = new javax.swing.JPanel();
        stokProdukBaruTextField = new javax.swing.JTextField();
        hargaProdukBaruLabel = new javax.swing.JLabel();
        tambahProdukLabel = new javax.swing.JLabel();
        namaProdukBaruLabel = new javax.swing.JLabel();
        addProductButton = new javax.swing.JButton();
        hargaProdukBaruTextField = new javax.swing.JTextField();
        namaProdukBaruTextField = new javax.swing.JTextField();
        stokProdukBaruLabel = new javax.swing.JLabel();
        hapusProdukPanel = new javax.swing.JPanel();
        hapusProdukLabel = new javax.swing.JLabel();
        produkHapusLabel = new javax.swing.JLabel();
        hapusProdukComboBox = new javax.swing.JComboBox<>();
        removeProductButton = new javax.swing.JButton();
        belanjaPanel = new javax.swing.JPanel();
        belanjaMenuPanel = new javax.swing.JPanel();
        belanjaLabel = new javax.swing.JLabel();
        tambahProdukButton = new javax.swing.JButton();
        returProdukButton = new javax.swing.JButton();
        lihatKeranjangButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();
        belanjaCardContainer = new javax.swing.JPanel();
        tambahProdukPanel = new javax.swing.JPanel();
        produkComboBox = new javax.swing.JComboBox<>();
        produkTambahKeranjangLabel = new javax.swing.JLabel();
        jumlahTambahKeranjangLabel = new javax.swing.JLabel();
        produkJumlahTextField = new javax.swing.JTextField();
        tambahButton = new javax.swing.JButton();
        tambahKeranjangLabel = new javax.swing.JLabel();
        returProdukPanel = new javax.swing.JPanel();
        returKeranjangLabel = new javax.swing.JLabel();
        produkReturKeranjangLabel = new javax.swing.JLabel();
        jumlahReturKeranjangLabel = new javax.swing.JLabel();
        returJumlahTextField = new javax.swing.JTextField();
        returButton = new javax.swing.JButton();
        returComboBox = new javax.swing.JComboBox<>();
        stokReturKeranjangLabel = new javax.swing.JLabel();
        returJumlahLabel = new javax.swing.JLabel();
        lihatKeranjangPanel = new javax.swing.JPanel();
        isiKeranjangLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        keranjangTable = new javax.swing.JTable();
        checkoutPanel = new javax.swing.JPanel();
        checkoutLabel = new javax.swing.JLabel();
        totalHargaCheckoutLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalHargaLabel = new javax.swing.JLabel();
        checkoutTextField = new javax.swing.JTextField();
        rpLabel = new javax.swing.JLabel();
        rpLabel1 = new javax.swing.JLabel();
        bayarButton = new javax.swing.JButton();
        firstPanelBelanja = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(850, 600));
        setName("mainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(850, 600));

        mainContainer.setBackground(new java.awt.Color(102, 102, 102));
        mainContainer.setLayout(new java.awt.CardLayout());

        loginLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        loginLabel.setText("LOGIN");
        loginLabel.setAlignmentY(0.0F);

        unameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unameLabel.setText("Username");

        passLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passLabel.setText("Password");

        unameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        passField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        loginButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        unameStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unameStatus.setForeground(new java.awt.Color(255, 51, 51));

        passStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passStatus.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(loginButton))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(loginLabel))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passLabel)
                            .addComponent(unameLabel))
                        .addGap(52, 52, 52)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(unameTextField)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passStatus)
                            .addComponent(unameStatus))))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(loginLabel)
                .addGap(25, 25, 25)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unameLabel)
                    .addComponent(unameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unameStatus))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passStatus))
                .addGap(31, 31, 31)
                .addComponent(loginButton)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        mainContainer.add(loginPanel, "loginCard");

        mainPanel.setBackground(new java.awt.Color(102, 102, 102));

        mainMenuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainMenuLabel.setText("Main Menu");
        mainMenuLabel.setAlignmentX(0.5F);
        mainMenuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        belanjaButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        belanjaButton.setText("Belanja");
        belanjaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belanjaButtonActionPerformed(evt);
            }
        });

        showTransactionsButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        showTransactionsButton.setText("Lihat Semua Transaksi");
        showTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTransactionsButtonActionPerformed(evt);
            }
        });

        restockButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        restockButton.setText("Restock Produk");
        restockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logoutButton.setText("Keluar");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        hapusProdukButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hapusProdukButton.setText("Hapus Produk");
        hapusProdukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusProdukButtonActionPerformed(evt);
            }
        });

        tambahProdukBaruButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambahProdukBaruButton.setText("Tambah Produk Baru");
        tambahProdukBaruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahProdukBaruButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(mainMenuLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(belanjaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showTransactionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(restockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusProdukButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahProdukBaruButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuLabel)
                .addGap(18, 18, 18)
                .addComponent(belanjaButton)
                .addGap(18, 18, 18)
                .addComponent(showTransactionsButton)
                .addGap(18, 18, 18)
                .addComponent(restockButton)
                .addGap(18, 18, 18)
                .addComponent(tambahProdukBaruButton)
                .addGap(18, 18, 18)
                .addComponent(hapusProdukButton)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainMenuCardContainer.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Easy Shopping in Minimarket");

        javax.swing.GroupLayout firstPanelMainMenuLayout = new javax.swing.GroupLayout(firstPanelMainMenu);
        firstPanelMainMenu.setLayout(firstPanelMainMenuLayout);
        firstPanelMainMenuLayout.setHorizontalGroup(
            firstPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        firstPanelMainMenuLayout.setVerticalGroup(
            firstPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(525, Short.MAX_VALUE))
        );

        mainMenuCardContainer.add(firstPanelMainMenu, "firstPanelMainMenuCard");

        daftarTransaskiLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        daftarTransaskiLabel.setText("Daftar Transaksi");
        daftarTransaskiLabel.setAlignmentX(0.5F);
        daftarTransaskiLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        transaksiTextArea.setColumns(20);
        transaksiTextArea.setRows(5);
        jScrollPane1.setViewportView(transaksiTextArea);

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiPanelLayout.createSequentialGroup()
                        .addComponent(daftarTransaskiLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE))
                .addContainerGap())
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(daftarTransaskiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainMenuCardContainer.add(transaksiPanel, "transaksiCard");

        restockProdukLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        restockProdukLabel.setText("Restock Produk");
        restockProdukLabel.setAlignmentX(0.5F);
        restockProdukLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        produkRestockLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        produkRestockLabel.setText("Produk");

        restockComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        restockComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        restockComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                restockComboBoxItemStateChanged(evt);
            }
        });

        jumlahRestockLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jumlahRestockLabel.setText("Jumlah");

        stokRestockLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        stokRestockLabel.setText("Stok produk: ");

        restockJumlahTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        restockProductButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        restockProductButton.setText("Restock Produk");
        restockProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockProductButtonActionPerformed(evt);
            }
        });

        restockJumlahLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        restockJumlahLabel.setText("0");

        javax.swing.GroupLayout restockPanelLayout = new javax.swing.GroupLayout(restockPanel);
        restockPanel.setLayout(restockPanelLayout);
        restockPanelLayout.setHorizontalGroup(
            restockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(restockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restockProdukLabel)
                    .addGroup(restockPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(produkRestockLabel)
                        .addGap(44, 44, 44)
                        .addGroup(restockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(restockPanelLayout.createSequentialGroup()
                                .addComponent(stokRestockLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restockJumlahLabel))
                            .addComponent(restockComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(restockPanelLayout.createSequentialGroup()
                        .addComponent(jumlahRestockLabel)
                        .addGap(44, 44, 44)
                        .addGroup(restockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restockJumlahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restockProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        restockPanelLayout.setVerticalGroup(
            restockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restockProdukLabel)
                .addGap(18, 18, 18)
                .addGroup(restockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produkRestockLabel)
                    .addComponent(restockComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(restockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stokRestockLabel)
                    .addComponent(restockJumlahLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(restockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahRestockLabel)
                    .addComponent(restockJumlahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(restockProductButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainMenuCardContainer.add(restockPanel, "restockCard");

        stokProdukBaruTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        hargaProdukBaruLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        hargaProdukBaruLabel.setText("Harga Produk");

        tambahProdukLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tambahProdukLabel.setText("Tambah Produk Baru");
        tambahProdukLabel.setAlignmentX(0.5F);
        tambahProdukLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        namaProdukBaruLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        namaProdukBaruLabel.setText("Nama Produk");

        addProductButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addProductButton.setText("Tambah Produk");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        hargaProdukBaruTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        namaProdukBaruTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        stokProdukBaruLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        stokProdukBaruLabel.setText("Stok Produk");

        javax.swing.GroupLayout tambahProdukBaruPanelLayout = new javax.swing.GroupLayout(tambahProdukBaruPanel);
        tambahProdukBaruPanel.setLayout(tambahProdukBaruPanelLayout);
        tambahProdukBaruPanelLayout.setHorizontalGroup(
            tambahProdukBaruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahProdukBaruPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahProdukBaruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahProdukLabel)
                    .addGroup(tambahProdukBaruPanelLayout.createSequentialGroup()
                        .addGroup(tambahProdukBaruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stokProdukBaruLabel)
                            .addComponent(namaProdukBaruLabel)
                            .addComponent(hargaProdukBaruLabel))
                        .addGap(32, 32, 32)
                        .addGroup(tambahProdukBaruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hargaProdukBaruTextField)
                            .addComponent(namaProdukBaruTextField)
                            .addComponent(stokProdukBaruTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tambahProdukBaruPanelLayout.setVerticalGroup(
            tambahProdukBaruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahProdukBaruPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahProdukLabel)
                .addGap(18, 18, 18)
                .addGroup(tambahProdukBaruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaProdukBaruLabel)
                    .addComponent(namaProdukBaruTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tambahProdukBaruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stokProdukBaruLabel)
                    .addComponent(stokProdukBaruTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tambahProdukBaruPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaProdukBaruLabel)
                    .addComponent(hargaProdukBaruTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addProductButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainMenuCardContainer.add(tambahProdukBaruPanel, "tambahProdukBaruCard");

        hapusProdukLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hapusProdukLabel.setText("Hapus Produk");
        hapusProdukLabel.setAlignmentX(0.5F);
        hapusProdukLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        produkHapusLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        produkHapusLabel.setText("Produk");

        hapusProdukComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        hapusProdukComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hapusProdukComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hapusProdukComboBoxItemStateChanged(evt);
            }
        });

        removeProductButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        removeProductButton.setText("Hapus Produk");
        removeProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hapusProdukPanelLayout = new javax.swing.GroupLayout(hapusProdukPanel);
        hapusProdukPanel.setLayout(hapusProdukPanelLayout);
        hapusProdukPanelLayout.setHorizontalGroup(
            hapusProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hapusProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hapusProdukLabel)
                    .addGroup(hapusProdukPanelLayout.createSequentialGroup()
                        .addComponent(produkHapusLabel)
                        .addGap(44, 44, 44)
                        .addComponent(hapusProdukComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hapusProdukPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(removeProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hapusProdukPanelLayout.setVerticalGroup(
            hapusProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hapusProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hapusProdukLabel)
                .addGap(18, 18, 18)
                .addGroup(hapusProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produkHapusLabel)
                    .addComponent(hapusProdukComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(removeProductButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainMenuCardContainer.add(hapusProdukPanel, "hapusProdukCard");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainMenuCardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenuCardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainContainer.add(mainPanel, "mainMenuCard");

        belanjaPanel.setBackground(new java.awt.Color(102, 102, 102));

        belanjaLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        belanjaLabel.setText("Belanja");
        belanjaLabel.setAlignmentX(0.5F);
        belanjaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tambahProdukButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambahProdukButton.setText("Tambah Produk");
        tambahProdukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahProdukButtonActionPerformed(evt);
            }
        });

        returProdukButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        returProdukButton.setText("Retur Produk");
        returProdukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returProdukButtonActionPerformed(evt);
            }
        });

        lihatKeranjangButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lihatKeranjangButton.setText("Lihat Keranjang");
        lihatKeranjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatKeranjangButtonActionPerformed(evt);
            }
        });

        checkoutButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        batalButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        batalButton.setText("Batal");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout belanjaMenuPanelLayout = new javax.swing.GroupLayout(belanjaMenuPanel);
        belanjaMenuPanel.setLayout(belanjaMenuPanelLayout);
        belanjaMenuPanelLayout.setHorizontalGroup(
            belanjaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belanjaMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(belanjaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returProdukButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lihatKeranjangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahProdukButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(batalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, belanjaMenuPanelLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(belanjaLabel)
                .addGap(110, 110, 110))
        );
        belanjaMenuPanelLayout.setVerticalGroup(
            belanjaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belanjaMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(belanjaLabel)
                .addGap(18, 18, 18)
                .addComponent(tambahProdukButton)
                .addGap(18, 18, 18)
                .addComponent(returProdukButton)
                .addGap(18, 18, 18)
                .addComponent(lihatKeranjangButton)
                .addGap(18, 18, 18)
                .addComponent(checkoutButton)
                .addGap(18, 18, 18)
                .addComponent(batalButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        belanjaCardContainer.setLayout(new java.awt.CardLayout());

        produkComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        produkTambahKeranjangLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        produkTambahKeranjangLabel.setText("Produk");

        jumlahTambahKeranjangLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jumlahTambahKeranjangLabel.setText("Jumlah");

        produkJumlahTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tambahButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tambahButton.setText("Masukkan ke keranjang");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        tambahKeranjangLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tambahKeranjangLabel.setText("Tambah Produk ke Keranjang");
        tambahKeranjangLabel.setAlignmentX(0.5F);
        tambahKeranjangLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout tambahProdukPanelLayout = new javax.swing.GroupLayout(tambahProdukPanel);
        tambahProdukPanel.setLayout(tambahProdukPanelLayout);
        tambahProdukPanelLayout.setHorizontalGroup(
            tambahProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahKeranjangLabel)
                    .addGroup(tambahProdukPanelLayout.createSequentialGroup()
                        .addGroup(tambahProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jumlahTambahKeranjangLabel)
                            .addComponent(produkTambahKeranjangLabel))
                        .addGap(44, 44, 44)
                        .addGroup(tambahProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tambahButton)
                            .addComponent(produkComboBox, 0, 425, Short.MAX_VALUE)
                            .addComponent(produkJumlahTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tambahProdukPanelLayout.setVerticalGroup(
            tambahProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahKeranjangLabel)
                .addGap(18, 18, 18)
                .addGroup(tambahProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produkTambahKeranjangLabel)
                    .addComponent(produkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tambahProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahTambahKeranjangLabel)
                    .addComponent(produkJumlahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tambahButton)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        belanjaCardContainer.add(tambahProdukPanel, "tambahProdukCard");

        returKeranjangLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        returKeranjangLabel.setText("Retur Produk dari Keranjang");
        returKeranjangLabel.setAlignmentX(0.5F);
        returKeranjangLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        produkReturKeranjangLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        produkReturKeranjangLabel.setText("Produk");

        jumlahReturKeranjangLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jumlahReturKeranjangLabel.setText("Jumlah");

        returJumlahTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        returButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        returButton.setText("Kembalikan Produk");
        returButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returButtonActionPerformed(evt);
            }
        });

        returComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        returComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        returComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                returComboBoxItemStateChanged(evt);
            }
        });

        stokReturKeranjangLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        stokReturKeranjangLabel.setText("Jumlah produk dalam keranjang: ");

        returJumlahLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        returJumlahLabel.setText("0");

        javax.swing.GroupLayout returProdukPanelLayout = new javax.swing.GroupLayout(returProdukPanel);
        returProdukPanel.setLayout(returProdukPanelLayout);
        returProdukPanelLayout.setHorizontalGroup(
            returProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returKeranjangLabel)
                    .addGroup(returProdukPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(produkReturKeranjangLabel)
                        .addGap(44, 44, 44)
                        .addGroup(returProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returProdukPanelLayout.createSequentialGroup()
                                .addComponent(stokReturKeranjangLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(returJumlahLabel))
                            .addComponent(returComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(returProdukPanelLayout.createSequentialGroup()
                        .addComponent(jumlahReturKeranjangLabel)
                        .addGap(44, 44, 44)
                        .addGroup(returProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returJumlahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        returProdukPanelLayout.setVerticalGroup(
            returProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returProdukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returKeranjangLabel)
                .addGap(18, 18, 18)
                .addGroup(returProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produkReturKeranjangLabel)
                    .addComponent(returComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(returProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stokReturKeranjangLabel)
                    .addComponent(returJumlahLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(returProdukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahReturKeranjangLabel)
                    .addComponent(returJumlahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(returButton)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        belanjaCardContainer.add(returProdukPanel, "returProdukCard");

        isiKeranjangLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        isiKeranjangLabel.setText("Isi Keranjang");
        isiKeranjangLabel.setAlignmentX(0.5F);
        isiKeranjangLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        keranjangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(keranjangTable);

        javax.swing.GroupLayout lihatKeranjangPanelLayout = new javax.swing.GroupLayout(lihatKeranjangPanel);
        lihatKeranjangPanel.setLayout(lihatKeranjangPanelLayout);
        lihatKeranjangPanelLayout.setHorizontalGroup(
            lihatKeranjangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatKeranjangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lihatKeranjangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lihatKeranjangPanelLayout.createSequentialGroup()
                        .addComponent(isiKeranjangLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
                .addContainerGap())
        );
        lihatKeranjangPanelLayout.setVerticalGroup(
            lihatKeranjangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lihatKeranjangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiKeranjangLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        belanjaCardContainer.add(lihatKeranjangPanel, "lihatKeranjangCard");

        checkoutLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        checkoutLabel.setText("Checkout");
        checkoutLabel.setAlignmentX(0.5F);
        checkoutLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totalHargaCheckoutLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        totalHargaCheckoutLabel.setText("Total Harga");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Bayar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText(":");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText(":");

        totalHargaLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        totalHargaLabel.setText("0");

        checkoutTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        rpLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rpLabel.setText("Rp.");

        rpLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rpLabel1.setText("Rp.");

        bayarButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bayarButton.setText("Checkout");
        bayarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
        checkoutPanel.setLayout(checkoutPanelLayout);
        checkoutPanelLayout.setHorizontalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalHargaCheckoutLabel)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkoutPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rpLabel1))
                            .addGroup(checkoutPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rpLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalHargaLabel)
                            .addComponent(checkoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(bayarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkoutLabel))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        checkoutPanelLayout.setVerticalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkoutLabel)
                .addGap(18, 18, 18)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalHargaCheckoutLabel)
                    .addComponent(jLabel3)
                    .addComponent(totalHargaLabel)
                    .addComponent(rpLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(checkoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rpLabel1))
                .addGap(18, 18, 18)
                .addComponent(bayarButton)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        belanjaCardContainer.add(checkoutPanel, "checkoutCard");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Easy Shopping in Minimarket");

        javax.swing.GroupLayout firstPanelBelanjaLayout = new javax.swing.GroupLayout(firstPanelBelanja);
        firstPanelBelanja.setLayout(firstPanelBelanjaLayout);
        firstPanelBelanjaLayout.setHorizontalGroup(
            firstPanelBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelBelanjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        firstPanelBelanjaLayout.setVerticalGroup(
            firstPanelBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelBelanjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(525, Short.MAX_VALUE))
        );

        belanjaCardContainer.add(firstPanelBelanja, "firstPanelBelanjaCard");

        javax.swing.GroupLayout belanjaPanelLayout = new javax.swing.GroupLayout(belanjaPanel);
        belanjaPanel.setLayout(belanjaPanelLayout);
        belanjaPanelLayout.setHorizontalGroup(
            belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belanjaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(belanjaMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(belanjaCardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        belanjaPanelLayout.setVerticalGroup(
            belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belanjaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(belanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(belanjaMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(belanjaCardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainContainer.add(belanjaPanel, "belanjaCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(mainContainer, "mainPanel");
        unameStatus.setText("");
        passStatus.setText("");
        String username = unameTextField.getText();
        String password = passField.getText();
        List<Kasir> kasirs = this.minimarket.getCashiers();
    	
    	boolean isLogin = false;
    	boolean isUsernameExist = false;
    	for(Kasir kasir : kasirs) {
            if(kasir.getUsernameKasir().equalsIgnoreCase(username)) {
                if(kasir.getUsernameKasir().equalsIgnoreCase(username) &&
                        kasir.getPasswordKasir().equalsIgnoreCase(password)) {
                    isUsernameExist = true;
                    isLogin = true;
                    chasier = kasir;
                    break;
                } else {
                    isUsernameExist = true;
                }
            }
    		
    		
    	}
    	
    	if(!isLogin) {
            if(!isUsernameExist) {
                unameStatus.setText("Username tidak ada");
            } else {
                passStatus.setText("Password salah");
            }
    	}
        else{
            //change card
            cardLayout.show(mainContainer, "mainMenuCard");
            mainMenuCardLayout.show(mainMenuCardContainer, "firstPanelMainMenuCard");
        }
        restockComboBox.setModel(new DefaultComboBoxModel(listProduk));
        hapusProdukComboBox.setModel(new DefaultComboBoxModel(listProduk));
    }//GEN-LAST:event_loginButtonActionPerformed

    private void belanjaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belanjaButtonActionPerformed
        // TODO add your handling code here:
        if(listProduk.length > 0){
            SimpleDateFormat sdf = new SimpleDateFormat("dd-mm-yy-HH-mm-ss");
        this.transaksi = new Transaksi(sdf.format(new Date()), this.chasier);
        cardLayout.show(mainContainer, "belanjaCard");
        belanjaCardLayout.show(belanjaCardContainer,"firstPanelBelanjaCard");
        }else{
            JOptionPane.showMessageDialog(msgbox, "Tidak ada produk");
            mainMenuCardLayout.show(mainMenuCardContainer, "tambahProdukBaruCard");
        }
        
    }//GEN-LAST:event_belanjaButtonActionPerformed

    private void showTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTransactionsButtonActionPerformed
        transaksiTextArea.setText("");
        boolean thereIsNoTransactions = true;
        for(Transaksi transaksi: minimarket.getTransactions()){
            transaksiTextArea.append("================================================\n");
            transaksiTextArea.append(transaksi.printData(transaksi.getKasir()));
            transaksiTextArea.append("================================================\n");
            thereIsNoTransactions = false;
        }
        if(thereIsNoTransactions) transaksiTextArea.append("Belum ada transaksi");
        mainMenuCardLayout.show(mainMenuCardContainer, "transaksiCard");
    }//GEN-LAST:event_showTransactionsButtonActionPerformed

    private void tambahProdukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahProdukButtonActionPerformed
        // TODO add your handling code here:
        produkComboBox.setModel(new DefaultComboBoxModel(this.listProduk));
        produkJumlahTextField.setText("");
        belanjaCardLayout.show(belanjaCardContainer,"tambahProdukCard");
    }//GEN-LAST:event_tambahProdukButtonActionPerformed

    private void returProdukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returProdukButtonActionPerformed
        // TODO add your handling code here:
        if(this.transaksi.getKeranjang().size()>0){
            returComboBox.setModel(new DefaultComboBoxModel(listKeranjang(this.transaksi)));
            int jumlah = transaksi.getKeranjang().get((Produk)returComboBox.getSelectedItem()).getJumlah_produk();
            returJumlahLabel.setText(""+jumlah);
            returJumlahTextField.setText("");
            belanjaCardLayout.show(belanjaCardContainer,"returProdukCard");
        }else{
            JOptionPane.showMessageDialog(msgbox, "Tidak ada Produk dalam keranjang");
        }
        
    }//GEN-LAST:event_returProdukButtonActionPerformed

    private void restockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restockButtonActionPerformed
        if(listProduk.length > 0){
            restockComboBox.setModel(new DefaultComboBoxModel(listProduk));
            restockJumlahLabel.setText(""+listProduk[restockComboBox.getSelectedIndex()].getStokProduk());
            restockJumlahTextField.setText("");
            mainMenuCardLayout.show(mainMenuCardContainer, "restockCard");
        }else{
            JOptionPane.showMessageDialog(msgbox, "Tidak ada produk");
            mainMenuCardLayout.show(mainMenuCardContainer, "tambahProdukBaruCard");
        }
    }//GEN-LAST:event_restockButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.chasier = null;
        unameTextField.setText("");
        passField.setText("");
        cardLayout.show(mainContainer, "loginCard");
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void lihatKeranjangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatKeranjangButtonActionPerformed
        // TODO add your handling code here
        if(this.transaksi.getKeranjang().size()>0){
            this.setTableKeranjang();
            belanjaCardLayout.show(belanjaCardContainer,"lihatKeranjangCard");
        }else{
            JOptionPane.showMessageDialog(msgbox, "Tidak ada Produk dalam keranjang");
        }
    }//GEN-LAST:event_lihatKeranjangButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        // TODO add your handling code here:
        if(this.transaksi.getKeranjang().size()>0){
            totalHargaLabel.setText(""+this.transaksi.getTotal_keseluruhan());
            belanjaCardLayout.show(belanjaCardContainer,"checkoutCard");
        }else{
            JOptionPane.showMessageDialog(msgbox, "Tidak ada Produk dalam keranjang");
        }
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        // TODO add your handling code here:
        if(this.transaksi.getKeranjang().size()>0){
            for(Map.Entry<Produk, Penjualan> entry : this.transaksi.getKeranjang().entrySet()){
                Produk key = entry.getKey();
                Penjualan value = entry.getValue();
                this.transaksi.removeFromKeranjang(key, value.getJumlah_produk());
            }
        }
        cardLayout.show(mainContainer, "mainMenuCard");
        mainMenuCardLayout.show(mainMenuCardContainer, "firstPanelMainMenuCard");
    }//GEN-LAST:event_batalButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        try {
            Produk selectedProduct = (Produk) produkComboBox.getSelectedItem();
            int jumlahProduk = Integer.parseInt(produkJumlahTextField.getText());
            if(selectedProduct.getStokProduk() >= jumlahProduk) {
                //Add selectedproduct to keranjang
                transaksi.addToKeranjang(selectedProduct, jumlahProduk);
                JOptionPane.showMessageDialog(msgbox, selectedProduct.getNamaProduk()+" sebanyak "+jumlahProduk+" berhasil dimasukkan ke dalam keranjang");
                produkComboBox.setModel(new DefaultComboBoxModel(this.listProduk));
            }else{
                JOptionPane.showMessageDialog(msgbox, "Stok untuk "+selectedProduct.getNamaProduk()+" kurang");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(msgbox, "Input tidak valid");
        }
        produkJumlahTextField.setText(""); 	
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void returButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returButtonActionPerformed
        try {
            Produk selectedProduct = (Produk) returComboBox.getSelectedItem();
            int jumlahProduk = Integer.parseInt(returJumlahTextField.getText());
            if(transaksi.getKeranjang().get(selectedProduct).getJumlah_produk()<jumlahProduk){
                JOptionPane.showMessageDialog(msgbox, "Jumlah "+selectedProduct.getNamaProduk()+" dalam keranjang kurang");
            }else{
                transaksi.removeFromKeranjang(selectedProduct, jumlahProduk);
                JOptionPane.showMessageDialog(msgbox, selectedProduct.getNamaProduk()+" sebanyak "+jumlahProduk+" berhasil dikembalikan");
                int jumlah = transaksi.getKeranjang().get((Produk)returComboBox.getSelectedItem()).getJumlah_produk();
                returJumlahLabel.setText(""+jumlah);
            }
            returComboBox.setModel(new DefaultComboBoxModel(listKeranjang(this.transaksi)));
            if(this.transaksi.getKeranjang().size()==0){
                belanjaCardLayout.show(belanjaCardContainer, "firstPanelBelanjaCard");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(msgbox, "Input tidak valid");
        }
        returJumlahTextField.setText("");
    }//GEN-LAST:event_returButtonActionPerformed

    private void returComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_returComboBoxItemStateChanged
        // TODO add your handling code here:
        int jumlah = transaksi.getKeranjang().get((Produk)returComboBox.getSelectedItem()).getJumlah_produk();
        returJumlahLabel.setText(""+jumlah);
    }//GEN-LAST:event_returComboBoxItemStateChanged

    private void bayarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarButtonActionPerformed
        try {
            double bayar = Double.parseDouble(checkoutTextField.getText());
            if(bayar >= this.transaksi.getTotal_keseluruhan()){
                this.transaksi.setUang(bayar);
                this.transaksi.printData(chasier);
                this.minimarket.getTransactions().add(this.transaksi); 
                JOptionPane.showMessageDialog(msgbox, this.transaksi.printData(chasier));
                cardLayout.show(mainContainer, "mainMenuCard");
                mainMenuCardLayout.show(mainMenuCardContainer, "firstPanelMainMenuCard");
            }else{
                JOptionPane.showMessageDialog(msgbox, "Uang Anda masih kurang!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(msgbox, "Input tidak valid");
        }
        checkoutTextField.setText("");
    }//GEN-LAST:event_bayarButtonActionPerformed

    private void restockComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_restockComboBoxItemStateChanged
        // TODO add your handling code here:
        restockJumlahLabel.setText(""+listProduk[restockComboBox.getSelectedIndex()].getStokProduk());
    }//GEN-LAST:event_restockComboBoxItemStateChanged

    private void restockProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restockProductButtonActionPerformed
        try {
            int stokTambahan = Integer.parseInt(restockJumlahTextField.getText());
            Produk selectedProduct = listProduk[restockComboBox.getSelectedIndex()];
            selectedProduct.setStokProduk(selectedProduct.getStokProduk()+ stokTambahan); 
            JOptionPane.showMessageDialog(msgbox, "Stok "+selectedProduct.getNamaProduk()+" sebanyak "+stokTambahan+" berhasil ditambahkan");
            restockJumlahLabel.setText(""+selectedProduct.getStokProduk());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(msgbox, "Input tidak valid");
        }
        restockJumlahTextField.setText("");
    }//GEN-LAST:event_restockProductButtonActionPerformed

    private void hapusProdukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusProdukButtonActionPerformed
        // TODO add your handling code here:
        if(listProduk.length > 0){
            hapusProdukComboBox.setModel(new DefaultComboBoxModel(listProduk));
            mainMenuCardLayout.show(mainMenuCardContainer, "hapusProdukCard");
        }else{
            JOptionPane.showMessageDialog(msgbox, "Tidak ada produk");
            mainMenuCardLayout.show(mainMenuCardContainer, "tambahProdukBaruCard");
        }
        
    }//GEN-LAST:event_hapusProdukButtonActionPerformed

    private void tambahProdukBaruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahProdukBaruButtonActionPerformed
        // TODO add your handling code here:
        namaProdukBaruTextField.setText("");
        stokProdukBaruTextField.setText("");
        hargaProdukBaruTextField.setText("");
        mainMenuCardLayout.show(mainMenuCardContainer, "tambahProdukBaruCard");
    }//GEN-LAST:event_tambahProdukBaruButtonActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        try {
            String namaProduk = namaProdukBaruTextField.getText();
            int stokProduk = Integer.parseInt(stokProdukBaruTextField.getText());
            double hargaProduk = Double.parseDouble(hargaProdukBaruTextField.getText());
            boolean uniqueProduct = true;
            for(Produk produk: this.listProduk){
                if(namaProduk.toLowerCase().equals(produk.getNamaProduk().toLowerCase())){
                    uniqueProduct = false;
                }
            }
            if(uniqueProduct){
                minimarket.addProduct(namaProduk, stokProduk, hargaProduk);
                JOptionPane.showMessageDialog(msgbox, "Produk berhasil ditambahkan");
                this.listProduk = minimarket.getProducts().toArray(new Produk[this.minimarket.getProducts().size()]);
            }else{
                JOptionPane.showMessageDialog(msgbox, "Produk telah tersedia");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(msgbox, "Input tidak valid");
        }
        namaProdukBaruTextField.setText("");
        stokProdukBaruTextField.setText("");
        hargaProdukBaruTextField.setText("");
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void hapusProdukComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hapusProdukComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusProdukComboBoxItemStateChanged

    private void removeProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProductButtonActionPerformed
        // TODO add your handling code here:
        Produk produk = (Produk) hapusProdukComboBox.getSelectedItem();
        minimarket.removeProduct(produk);
        JOptionPane.showMessageDialog(msgbox, "Produk berhasil dihapus");
        this.listProduk = minimarket.getProducts().toArray(new Produk[this.minimarket.getProducts().size()]);
        if(listProduk.length > 0){
            hapusProdukComboBox.setModel(new DefaultComboBoxModel(listProduk));    
        }else{
            mainMenuCardLayout.show(mainMenuCardContainer, "firstPanelMainMenuCard");
        }
    }//GEN-LAST:event_removeProductButtonActionPerformed
    
    public Produk[] listKeranjang(Transaksi transaksi){
//        minimarket.getProducts().toArray(new Produk[minimarket.getProducts().size()])
        Produk produk[] = this.transaksi.getKeranjang().keySet().toArray(new Produk[this.transaksi.getKeranjang().keySet().size()]);
        return produk;
    }
    
    public void setTableKeranjang(){
        String[][] data = new String[this.transaksi.getKeranjang().size()][3];
        String[] kolom = {"Nama Produk", "Jumlah", "Total Harga"};
        int index = 0;
        for(Map.Entry<Produk, Penjualan> entry: this.transaksi.getKeranjang().entrySet()){
            String namaProduk = entry.getKey().getNamaProduk();
            int jumlah = entry.getValue().getJumlah_produk();
            double total = entry.getValue().getTotal_harga();
            data[index][0] = entry.getKey().getNamaProduk();
            data[index][1] = ""+entry.getValue().getJumlah_produk();
            data[index][2] = "Rp."+entry.getValue().getTotal_harga();
            index++;
        }
        keranjangTable.setModel(new DefaultTableModel(data,kolom));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton batalButton;
    private javax.swing.JButton bayarButton;
    private javax.swing.JButton belanjaButton;
    private javax.swing.JPanel belanjaCardContainer;
    private javax.swing.JLabel belanjaLabel;
    private javax.swing.JPanel belanjaMenuPanel;
    private javax.swing.JPanel belanjaPanel;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JLabel checkoutLabel;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JTextField checkoutTextField;
    private javax.swing.JLabel daftarTransaskiLabel;
    private javax.swing.JPanel firstPanelBelanja;
    private javax.swing.JPanel firstPanelMainMenu;
    private javax.swing.JButton hapusProdukButton;
    private javax.swing.JComboBox<String> hapusProdukComboBox;
    private javax.swing.JLabel hapusProdukLabel;
    private javax.swing.JPanel hapusProdukPanel;
    private javax.swing.JLabel hargaProdukBaruLabel;
    private javax.swing.JTextField hargaProdukBaruTextField;
    private javax.swing.JLabel isiKeranjangLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jumlahRestockLabel;
    private javax.swing.JLabel jumlahReturKeranjangLabel;
    private javax.swing.JLabel jumlahTambahKeranjangLabel;
    private javax.swing.JTable keranjangTable;
    private javax.swing.JButton lihatKeranjangButton;
    private javax.swing.JPanel lihatKeranjangPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel mainMenuCardContainer;
    private javax.swing.JLabel mainMenuLabel;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaProdukBaruLabel;
    private javax.swing.JTextField namaProdukBaruTextField;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passStatus;
    private javax.swing.JComboBox<String> produkComboBox;
    private javax.swing.JLabel produkHapusLabel;
    private javax.swing.JTextField produkJumlahTextField;
    private javax.swing.JLabel produkRestockLabel;
    private javax.swing.JLabel produkReturKeranjangLabel;
    private javax.swing.JLabel produkTambahKeranjangLabel;
    private javax.swing.JButton removeProductButton;
    private javax.swing.JButton restockButton;
    private javax.swing.JComboBox<String> restockComboBox;
    private javax.swing.JLabel restockJumlahLabel;
    private javax.swing.JTextField restockJumlahTextField;
    private javax.swing.JPanel restockPanel;
    private javax.swing.JButton restockProductButton;
    private javax.swing.JLabel restockProdukLabel;
    private javax.swing.JButton returButton;
    private javax.swing.JComboBox<String> returComboBox;
    private javax.swing.JLabel returJumlahLabel;
    private javax.swing.JTextField returJumlahTextField;
    private javax.swing.JLabel returKeranjangLabel;
    private javax.swing.JButton returProdukButton;
    private javax.swing.JPanel returProdukPanel;
    private javax.swing.JLabel rpLabel;
    private javax.swing.JLabel rpLabel1;
    private javax.swing.JButton showTransactionsButton;
    private javax.swing.JLabel stokProdukBaruLabel;
    private javax.swing.JTextField stokProdukBaruTextField;
    private javax.swing.JLabel stokRestockLabel;
    private javax.swing.JLabel stokReturKeranjangLabel;
    private javax.swing.JButton tambahButton;
    private javax.swing.JLabel tambahKeranjangLabel;
    private javax.swing.JButton tambahProdukBaruButton;
    private javax.swing.JPanel tambahProdukBaruPanel;
    private javax.swing.JButton tambahProdukButton;
    private javax.swing.JLabel tambahProdukLabel;
    private javax.swing.JPanel tambahProdukPanel;
    private javax.swing.JLabel totalHargaCheckoutLabel;
    private javax.swing.JLabel totalHargaLabel;
    private javax.swing.JPanel transaksiPanel;
    private javax.swing.JTextArea transaksiTextArea;
    private javax.swing.JLabel unameLabel;
    private javax.swing.JLabel unameStatus;
    private javax.swing.JTextField unameTextField;
    // End of variables declaration//GEN-END:variables
}
